#!/usr/bin/env python3
import argparse
import re
import sys
from pathlib import Path


INCLUDE_RE = re.compile(r'^\s*#\s*include\s*([<"])([^>"]+)[>"].*$')


def include_dirs(repo: Path) -> list[Path]:
    dirs = [repo / "include", repo / "lib"]
    if (repo / "lib").is_dir():
        for child in sorted((repo / "lib").iterdir()):
            if child.is_dir():
                dirs.append(child)
                inc = child / "include"
                if inc.is_dir():
                    dirs.append(inc)
    return dirs


def find_include(name: str, current_dir: Path, dirs: list[Path]) -> Path | None:
    candidates = [current_dir] + dirs
    for base in candidates:
        path = (base / name).resolve()
        if path.is_file():
            return path
    return None


def expand_file(path: Path, dirs: list[Path], seen: set[Path], stack: list[Path]) -> list[str]:
    path = path.resolve()
    if path in seen:
        return []
    if path in stack:
        cycle = " -> ".join(str(p) for p in stack + [path])
        raise RuntimeError(f"cyclic include detected: {cycle}")

    seen.add(path)
    stack.append(path)

    output: list[str] = []
    for raw in path.read_text().splitlines(keepends=True):
        stripped = raw.strip()
        if stripped == "#pragma once":
            continue

        match = INCLUDE_RE.match(raw)
        if not match:
            output.append(raw)
            continue

        opener = match.group(1)
        include_name = match.group(2)
        include_path = find_include(include_name, path.parent, dirs)
        if include_path is None:
            if opener == "<":
                output.append(raw)
                continue
            raise FileNotFoundError(f'{path}: local include not found: "{include_name}"')

        output.append(f"// begin include: {include_name}\n")
        output.extend(expand_file(include_path, dirs, seen, stack))
        if output and not output[-1].endswith("\n"):
            output.append("\n")
        output.append(f"// end include: {include_name}\n")

    stack.pop()
    return output


def main() -> int:
    parser = argparse.ArgumentParser(description="Expand local C++ includes for AOJ submission.")
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--repo", type=Path, default=Path.cwd())
    args = parser.parse_args()

    repo = args.repo.resolve()
    source = (repo / args.source).resolve() if not args.source.is_absolute() else args.source.resolve()
    output = (repo / args.output).resolve() if not args.output.is_absolute() else args.output.resolve()

    if not source.is_file():
        print(f"source not found: {source}", file=sys.stderr)
        return 1

    try:
        expanded = expand_file(source, include_dirs(repo), set(), [])
    except Exception as exc:
        print(f"expand failed: {exc}", file=sys.stderr)
        return 1

    output.parent.mkdir(parents=True, exist_ok=True)
    header = [
        f"// Generated from {source.relative_to(repo)} for AOJ submission.\n",
        "// Do not edit this file directly.\n",
        "\n",
    ]
    output.write_text("".join(header + expanded))
    print(output.relative_to(repo))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
